In [0]:
import numpy as np
import pandas as pd


def sigmoid(S):
  return 1/(1 + np.exp(-S))

def regression_fit(w_init, X, y, lamda, lr, epoches=2000):
  w = w_old = w_init
  ep = 0
  N, d = X.shape[0], X.shape[1]
  while ep < epoches:
      mix_ids = np.random.permutation(N)
      ep += 1
      for i in mix_ids:
          xi = X[i]
          yi = y[i]
          zi = sigmoid(xi.dot(w))
          w = w - lr*((zi-yi)*xi + lamda*w)
      print(ep)
      if np.linalg.norm(w - w_old)/d < 1e-6:
          break
  w_old = w
  return w


In [2]:
n_inputs = 4
file_path_old = "../content/drive/My Drive/VDK/data/danangdaily2019.csv"
file_path_new = []
file_path_new.append("../content/drive/My Drive/VDK/data/danangdaily.csv")
file_path_new.append("../content/drive/My Drive/VDK/data/danangdaily1.csv")
file_path_new.append( "../content/drive/My Drive/VDK/data/danangdaily2.csv")
file_path_new.append( "../content/drive/My Drive/VDK/data/danangdaily3.csv")
def read_data(file_path):
  data=pd.read_csv(file_path, delimiter=',',header=11,skipinitialspace=True, usecols=['Temperature', 'Relative Humidity', 'Mean Sea Level Pressure', 'Total Precipitation'] )
  X = np.array(data)
  X[X[:, n_inputs - 1 ]/2 >= 0.3, n_inputs -1] = 1
  X[X[:, n_inputs - 1 ]/2 < 0.3, n_inputs -1] = 0
  return X
X_train = read_data(file_path_old)
y_train = X_train[1:,n_inputs - 1]
X_train = X_train[:-1]

X_test = np.empty((0,n_inputs))
y_test = np.empty((0))
for path in file_path_new:
  print(path)
  data = read_data(path)
  target = data[1:, n_inputs - 1]
  data = data[:-1]
  X_test = np.concatenate((X_test, data), axis = 0)
  y_test = np.concatenate((y_test, target)) 
# temperature = np.array(data["Temperature"]).reshape(-1, 1)
# relative_humidity = np.array(data["Relative Humidity"]).reshape(-1, 1)
# MSLP = np.array(data["Mean Sea Level Pressure"]).reshape(-1, 1)
# precipitation_total = np.array(data["Precipitation Total"]).reshape(-1, 1)
# X = np.concatenate((temperature, relative_humidity, MSLP, precipitation_total), axis = 1)



Xbar = np.concatenate((X_train, np.ones((X_train.shape[0], 1))), axis=1)
w_init = np.random.randn(Xbar.shape[1])
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
print(X_train)


../content/drive/My Drive/VDK/data/danangdaily.csv
../content/drive/My Drive/VDK/data/danangdaily1.csv
../content/drive/My Drive/VDK/data/danangdaily2.csv
../content/drive/My Drive/VDK/data/danangdaily3.csv
(364, 4) (364,) (56, 4) (56,)
[[2.05197320e+01 8.71122060e+01 1.02141670e+03 1.00000000e+00]
 [2.06488970e+01 8.84133400e+01 1.02046246e+03 1.00000000e+00]
 [2.10126510e+01 9.03534000e+01 1.01958746e+03 1.00000000e+00]
 ...
 [2.29338970e+01 8.96817600e+01 1.01655830e+03 1.00000000e+00]
 [2.36330660e+01 8.80373300e+01 1.01581250e+03 1.00000000e+00]
 [2.38326500e+01 9.03114300e+01 1.01677910e+03 1.00000000e+00]]


In [0]:
w = regression_fit(w_init, Xbar, y_train, 0.001, 0.1, 200000)
print(w)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: overflow encountered in exp
  


Streaming output truncated to the last 5000 lines.
44490
44491
44492
44493
44494
44495
44496
44497
44498
44499
44500
44501
44502
44503
44504
44505
44506
44507
44508
44509
44510
44511
44512
44513
44514
44515
44516
44517
44518
44519
44520
44521
44522
44523
44524
44525
44526
44527
44528
44529
44530
44531
44532
44533
44534
44535
44536
44537
44538
44539
44540
44541
44542
44543
44544
44545
44546
44547
44548
44549
44550
44551
44552
44553
44554
44555
44556
44557
44558
44559
44560
44561
44562
44563
44564
44565
44566
44567
44568
44569
44570
44571
44572
44573
44574
44575
44576
44577
44578
44579
44580
44581
44582
44583
44584
44585
44586
44587
44588
44589
44590
44591
44592
44593
44594
44595
44596
44597
44598
44599
44600
44601
44602
44603
44604
44605
44606
44607
44608
44609
44610
44611
44612
44613
44614
44615
44616
44617
44618
44619
44620
44621
44622
44623
44624
44625
44626
44627
44628
44629
44630
44631
44632
44633
44634
44635
44636
44637
44638
44639
44640
44641
44642
44643
44644
44645
44646
44647
4

In [0]:
w = np.array([-1.63516169e+02,  6.43116851e+02, -6.85527415e+01,  1.37051918e+02,
 -1.34784569e-01])
Xbar_test = np.concatenate((X_test, np.ones((X_test.shape[0], 1))), axis=1)
print(Xbar_test.shape)
z = sigmoid(Xbar_test.dot(w))
# z[z>=0.9] = 1
# z[z<0.9] = 0
print(z)

In [0]:
print(100*np.mean(z==y_test))
print(y_test)

In [0]:
file = "../content/drive/My Drive/VDK/data/danangdaily.csv"
M = read_data(file)
M[M[:, 3]>0, 3] = 1
N = M[1:, 3]
M = M[:-1]
M = np.concatenate((M, np.ones((M.shape[0], 1))), axis = 1)
k = sigmoid(M.dot(w))
k[k>=0.5] = 1
k[k<0.5] = 0
print(100*np.mean(k==N))
