In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

N = 10


def predict(w, X):
    return np.sign(X.dot(w))


def myPerceptron(X, y, w_init):
    w = w_init
    while True:
        pred = predict(w, X)
        mis_idxs = np.where(np.equal(pred, y) == False)[0]
        print(mis_idxs.shape)
        if mis_idxs.shape[0] < 60:
            return w
        random_id = np.random.choice(mis_idxs, 1)[0]
        w = w + y[random_id]*X[random_id]


# means = [[-1, 0], [1, 0]]
# cov = [[0.2, 0.3], [0.3, 0.2]]
# X1 = np.random.multivariate_normal(means[0], cov, N)
# X2 = np.random.multivariate_normal(means[1], cov, N)
# X = np.concatenate((X1, X2), axis=0)
# y = np.concatenate((np.ones(N), -1*np.ones(N)))
# Xbar = np.concatenate((np.ones((2*N, 1)), X), axis=1)
# print(X, y)

# w_init = np.random.randn(Xbar.shape[1])
# w = myPerceptron(Xbar, y, w_init)
# plt.plot(X1[:, 0], X1[:, 1], "go", X2[:, 0], X2[:, 1], "r^")
# plt.show()
# print(w)


In [14]:
n_inputs = 4
file_path_old = "../content/drive/My Drive/VDK/data/danangdaily2019.csv"
file_path_new = []
file_path_new.append("../content/drive/My Drive/VDK/data/danangdaily.csv")
file_path_new.append("../content/drive/My Drive/VDK/data/danangdaily1.csv")
file_path_new.append( "../content/drive/My Drive/VDK/data/danangdaily2.csv")
file_path_new.append( "../content/drive/My Drive/VDK/data/danangdaily3.csv")
def read_data(file_path):
  data=pd.read_csv(file_path, delimiter=',',header=11,skipinitialspace=True, usecols=['Temperature', 'Relative Humidity', 'Mean Sea Level Pressure', 'Total Precipitation'] )
  X = np.array(data)
  X[X[:, n_inputs - 1 ]/2 >= 0.3, n_inputs -1] = 1
  X[X[:, n_inputs - 1 ]/2 < 0.3, n_inputs -1] = -1
  return X
X_train = read_data(file_path_old)
y_train = X_train[1:,n_inputs - 1]
X_train = X_train[:-1]

X_test = np.empty((0,n_inputs))
y_test = np.empty((0))
for path in file_path_new:
  print(path)
  data = read_data(path)
  target = data[1:, n_inputs - 1]
  data = data[:-1]
  X_test = np.concatenate((X_test, data), axis = 0)
  y_test = np.concatenate((y_test, target)) 
# temperature = np.array(data["Temperature"]).reshape(-1, 1)
# relative_humidity = np.array(data["Relative Humidity"]).reshape(-1, 1)
# MSLP = np.array(data["Mean Sea Level Pressure"]).reshape(-1, 1)
# precipitation_total = np.array(data["Precipitation Total"]).reshape(-1, 1)
# X = np.concatenate((temperature, relative_humidity, MSLP, precipitation_total), axis = 1)



Xbar = np.concatenate((X_train, np.ones((X_train.shape[0], 1))), axis=1)
w_init = np.random.randn(Xbar.shape[1])
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
print(X_train)

../content/drive/My Drive/VDK/data/danangdaily.csv
../content/drive/My Drive/VDK/data/danangdaily1.csv
../content/drive/My Drive/VDK/data/danangdaily2.csv
../content/drive/My Drive/VDK/data/danangdaily3.csv
(364, 4) (364,) (56, 4) (56,)
[[2.05197320e+01 8.71122060e+01 1.02141670e+03 1.00000000e+00]
 [2.06488970e+01 8.84133400e+01 1.02046246e+03 1.00000000e+00]
 [2.10126510e+01 9.03534000e+01 1.01958746e+03 1.00000000e+00]
 ...
 [2.29338970e+01 8.96817600e+01 1.01655830e+03 1.00000000e+00]
 [2.36330660e+01 8.80373300e+01 1.01581250e+03 1.00000000e+00]
 [2.38326500e+01 9.03114300e+01 1.01677910e+03 1.00000000e+00]]


In [0]:
w = myPerceptron(Xbar, y_train, w_init)
X_test_bar = np.concatenate((X_test, np.ones((X_test.shape[0], 1))), axis=1)
z = predict(w, X_test_bar)
print(100*np.mean(z==y_test))

Streaming output truncated to the last 5000 lines.
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
(76,)
(167,)
(76,)
(167,)
(76,)
(167,)
(76,)
(167,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(197,)
(76,)
(197,)
(76,)
(197,)
(76,)
(167,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
(76,)
(167,)
(76,)
(167,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
(76,)
(167,)
(76,)
(167,)
(76,)
(197,)
(76,)
(167,)
